server:
  port: 10031

zuul:
  add-host-header: true
  ignoredServices: '*'
  routes:
    route-zuul:
      path: /zuul/**
      serviceId: zuul
      retryable: true
    route-test:
      path: /demo/**
      serviceId: minion-demo
      retryable: true

times: 104