spring:
  mail:
    host: smtp.qq.com
    username: 469741414@qq.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: 469741414@qq.com
          to: 469741414@qq.com

server:
  port: 10011

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10001/eureka/

management:
  security:
    enabled: false